if(NOT WIN32)
    string(ASCII 27 Esc)
    set(COLOUR_RESET "${Esc}[m")
    set(COLOUR_BOLD  "${Esc}[1m")
    set(RED         "${Esc}[31m")
    set(GREEN       "${Esc}[32m")
    set(YELLOW      "${Esc}[33m")
    set(BLUE        "${Esc}[34m")
    set(MAGENTA     "${Esc}[35m")
    set(CYAN        "${Esc}[36m")
    set(WHITE       "${Esc}[37m")
    set(BOLD_RED     "${Esc}[1;31m")
    set(BOLD_GREEN   "${Esc}[1;32m")
    set(BOLD_YELLOW  "${Esc}[1;33m")
    set(BOLD_BLUE    "${Esc}[1;34m")
    set(BOLD_MAGENTA "${Esc}[1;35m")
    set(BOLD_CYAN    "${Esc}[1;36m")
    set(BOLD_WHITE   "${Esc}[1;37m")
endif()

macro(message_color_mode MESSAGE COLOR MODE)
    if(NOT WIN32)
        message(${MODE} "${${COLOR}}${MESSAGE}${COLOUR_RESET}")
    elseif()
        message(${MODE} "${MESSAGE}")
    endif()
endmacro()

macro(message_color MESSAGE COLOR)
    message_color_mode(${MESSAGE} ${COLOR} NOTICE)
endmacro()

# Examples
#message("This is normal")
#message("${Red}This is Red${ColourReset}")
#message("${Green}This is Green${ColourReset}")
#message("${Yellow}This is Yellow${ColourReset}")
#message("${Blue}This is Blue${ColourReset}")
#message("${Magenta}This is Magenta${ColourReset}")
#message("${Cyan}This is Cyan${ColourReset}")
#message("${White}This is White${ColourReset}")
#message("${BoldRed}This is BoldRed${ColourReset}")
#message("${BoldGreen}This is BoldGreen${ColourReset}")
#message("${BoldYellow}This is BoldYellow${ColourReset}")
#message("${BoldBlue}This is BoldBlue${ColourReset}")
#message("${BoldMagenta}This is BoldMagenta${ColourReset}")
#message("${BoldCyan}This is BoldCyan${ColourReset}")
#message("${BoldWhite}This is BoldWhite\n\n${ColourReset}")